/**
 * This file is required for Genkit to work with Next.js.
 * It is automatically generated by Genkit and should not be modified.
 */
import {nextHandler} from '@genkit-ai/next';
export const GET = nextHandler();
export const POST = nextHandler();
